### 列表操作
# @prompt id 论坛编号
GET /Forums/{{id}}/Users?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 新增操作
# @prompt forumId 论坛编号
# @prompt userId  用户编号
POST /Forums/{{forumId}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

[
	{
		"UserId": {{userId}},
		"Permission": "All"
	}
]

### 增改操作
# @prompt forumId 论坛编号
# @prompt userId  用户编号
PUT /Forums/{{forumId}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

[
	{
		"UserId": {{userId}},
		"Permission": "All"
	}
]

### 更新操作
# @prompt forumId 论坛编号
# @prompt userId  用户编号
PATCH /Forums/{{forumId}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

[
	{
		"UserId": {{userId}},
		"Permission": "All"
	}
]

### 删除操作
# @prompt forumId 论坛编号
# @prompt userId  用户编号
DELETE /Forums/Users/{{forumId}}-{{userId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 批量删除
DELETE /Forums/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

404-1,404-2,404-3

### 清空操作
# @prompt id 论坛编号
DELETE /Forums/{{id}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
