### 列表操作
GET /Forums?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 模式查询
GET /Forums/Visibility:all+CreatedTime:thisyear?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 查询操作
### 注：有关查询条件请参考对应的条件实体类的定义。
POST /Forums/Query?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

{
	"Name": "%",
	"IsPopular": true,
	"TotalThreads": "0~9999999",
	"CreatedTime": "thisyear()"
}

### 编号查询
# @prompt id 论坛编号
GET /Forums/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 创建操作
# @prompt name 论坛名称
POST /Forums HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}"
}

### 更新操作
# @prompt id    论坛编号
# @prompt field 字段名称
# @prompt value 字段内容
PATCH /Forums/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"{{field}}": "{{value}}"
}

### 删除操作
# @prompt id 论坛编号
DELETE /Forums/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 批量删除
DELETE /Forums HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: text/plain

401,402,403

### 导出操作
GET /Forums/Export?format=spreadsheet HTTP/1.1
Host: {{host}}:{{port}}
X-Data-Schema: *
X-Export-Fields: *
Authorization: Credential {{$dotenv credentialId}}
