### 列表操作
GET /Threads?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 模式查询
GET /Threads/IsLocked:false+IsValued:true+CreatedTime:thisyear?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 查询操作
### 注：有关查询条件请参考对应的条件实体类的定义。
POST /Threads/Query?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

{
	"Approved": true,
	"IsLocked": false,
	"TotalReplies": "0~999999",
	"CreatedTime": "thisyear()"
}

### 编号查询
# @prompt id 主题编号
GET /Threads/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 创建操作
# @prompt title 主题标题
POST /Threads HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"Title": "{{title}}"
}

### 更新操作
# @prompt id    主题编号
# @prompt field 字段名称
# @prompt value 字段内容
PATCH /Threads/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"{{field}}": "{{value}}"
}

### 删除操作
# @prompt id 主题编号
DELETE /Threads/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 批量删除
DELETE /Threads HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: text/plain

401,402,403

### 导出操作
GET /Threads/Export?format=spreadsheet HTTP/1.1
Host: {{host}}:{{port}}
X-Data-Schema: *
X-Export-Fields: *
Authorization: Credential {{$dotenv credentialId}}
