//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Community.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Community.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 可访问性 的本地化字符串。
        /// </summary>
        internal static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部人员 的本地化字符串。
        /// </summary>
        internal static string Accessibility_Internal {
            get {
                return ResourceManager.GetString("Accessibility.Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版主 的本地化字符串。
        /// </summary>
        internal static string Accessibility_Moderator {
            get {
                return ResourceManager.GetString("Accessibility.Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限定人员 的本地化字符串。
        /// </summary>
        internal static string Accessibility_Specified {
            get {
                return ResourceManager.GetString("Accessibility.Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩写 的本地化字符串。
        /// </summary>
        internal static string Acronym {
            get {
                return ResourceManager.GetString("Acronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否审核 的本地化字符串。
        /// </summary>
        internal static string Approvable {
            get {
                return ResourceManager.GetString("Approvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已审核 的本地化字符串。
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核时间 的本地化字符串。
        /// </summary>
        internal static string ApprovedTime {
            get {
                return ResourceManager.GetString("ApprovedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件目录 的本地化字符串。
        /// </summary>
        internal static string AttachmentFolder {
            get {
                return ResourceManager.GetString("AttachmentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件目录编号 的本地化字符串。
        /// </summary>
        internal static string AttachmentFolderId {
            get {
                return ResourceManager.GetString("AttachmentFolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件编号 的本地化字符串。
        /// </summary>
        internal static string AttachmentId {
            get {
                return ResourceManager.GetString("AttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区论坛 的本地化字符串。
        /// </summary>
        internal static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供社区站点、论坛、主题、发帖等功能。 的本地化字符串。
        /// </summary>
        internal static string Community_Description {
            get {
                return ResourceManager.GetString("Community.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人名 的本地化字符串。
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系方式 的本地化字符串。
        /// </summary>
        internal static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容类型 的本地化字符串。
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面图片 的本地化字符串。
        /// </summary>
        internal static string CoverPicture {
            get {
                return ResourceManager.GetString("CoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面路径 的本地化字符串。
        /// </summary>
        internal static string CoverPicturePath {
            get {
                return ResourceManager.GetString("CoverPicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人编号 的本地化字符串。
        /// </summary>
        internal static string CreatorId {
            get {
                return ResourceManager.GetString("CreatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述说明 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领域 的本地化字符串。
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮箱 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期时间 的本地化字符串。
        /// </summary>
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈 的本地化字符串。
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈编号 的本地化字符串。
        /// </summary>
        internal static string FeedbackId {
            get {
                return ResourceManager.GetString("FeedbackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名称 的本地化字符串。
        /// </summary>
        internal static string File_Name {
            get {
                return ResourceManager.GetString("File.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        internal static string File_Size {
            get {
                return ResourceManager.GetString("File.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件类型 的本地化字符串。
        /// </summary>
        internal static string File_Type {
            get {
                return ResourceManager.GetString("File.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件编号 的本地化字符串。
        /// </summary>
        internal static string FileId {
            get {
                return ResourceManager.GetString("FileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名称 的本地化字符串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件类型 的本地化字符串。
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首次浏览时间 的本地化字符串。
        /// </summary>
        internal static string FirstViewedTime {
            get {
                return ResourceManager.GetString("FirstViewedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录编号 的本地化字符串。
        /// </summary>
        internal static string FolderId {
            get {
                return ResourceManager.GetString("FolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 论坛 的本地化字符串。
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 论坛组 的本地化字符串。
        /// </summary>
        internal static string Forum_Group {
            get {
                return ResourceManager.GetString("Forum.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 论坛组号 的本地化字符串。
        /// </summary>
        internal static string Forum_GroupId {
            get {
                return ResourceManager.GetString("Forum.GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 论坛组 的本地化字符串。
        /// </summary>
        internal static string ForumGroup {
            get {
                return ResourceManager.GetString("ForumGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 论坛组号 的本地化字符串。
        /// </summary>
        internal static string ForumGroupId {
            get {
                return ResourceManager.GetString("ForumGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 论坛编号 的本地化字符串。
        /// </summary>
        internal static string ForumId {
            get {
                return ResourceManager.GetString("ForumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女士 的本地化字符串。
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男士 的本地化字符串。
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未定义 的本地化字符串。
        /// </summary>
        internal static string Gender_None {
            get {
                return ResourceManager.GetString("Gender.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Gender_Unknown {
            get {
                return ResourceManager.GetString("Gender.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机域名 的本地化字符串。
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否全局 的本地化字符串。
        /// </summary>
        internal static string IsGlobal {
            get {
                return ResourceManager.GetString("IsGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否锁定 的本地化字符串。
        /// </summary>
        internal static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否版主 的本地化字符串。
        /// </summary>
        internal static string IsModerator {
            get {
                return ResourceManager.GetString("IsModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否置顶 的本地化字符串。
        /// </summary>
        internal static string IsPinned {
            get {
                return ResourceManager.GetString("IsPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否热门 的本地化字符串。
        /// </summary>
        internal static string IsPopular {
            get {
                return ResourceManager.GetString("IsPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否已读 的本地化字符串。
        /// </summary>
        internal static string IsRead {
            get {
                return ResourceManager.GetString("IsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否精华 的本地化字符串。
        /// </summary>
        internal static string IsValued {
            get {
                return ResourceManager.GetString("IsValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后浏览时间 的本地化字符串。
        /// </summary>
        internal static string LastViewedTime {
            get {
                return ResourceManager.GetString("LastViewedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接地址 的本地化字符串。
        /// </summary>
        internal static string LinkUrl {
            get {
                return ResourceManager.GetString("LinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息编号 的本地化字符串。
        /// </summary>
        internal static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息类型 的本地化字符串。
        /// </summary>
        internal static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后回帖作者 的本地化字符串。
        /// </summary>
        internal static string MostRecentPostAuthor {
            get {
                return ResourceManager.GetString("MostRecentPostAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后回帖作者头像 的本地化字符串。
        /// </summary>
        internal static string MostRecentPostAuthorAvatar {
            get {
                return ResourceManager.GetString("MostRecentPostAuthorAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后回帖作者编号 的本地化字符串。
        /// </summary>
        internal static string MostRecentPostAuthorId {
            get {
                return ResourceManager.GetString("MostRecentPostAuthorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后回帖作者名称 的本地化字符串。
        /// </summary>
        internal static string MostRecentPostAuthorName {
            get {
                return ResourceManager.GetString("MostRecentPostAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后回帖编号 的本地化字符串。
        /// </summary>
        internal static string MostRecentPostId {
            get {
                return ResourceManager.GetString("MostRecentPostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后回帖时间 的本地化字符串。
        /// </summary>
        internal static string MostRecentPostTime {
            get {
                return ResourceManager.GetString("MostRecentPostTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近主题作者 的本地化字符串。
        /// </summary>
        internal static string MostRecentThreadAuthor {
            get {
                return ResourceManager.GetString("MostRecentThreadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近主题作者头像 的本地化字符串。
        /// </summary>
        internal static string MostRecentThreadAuthorAvatar {
            get {
                return ResourceManager.GetString("MostRecentThreadAuthorAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近主题作者编号 的本地化字符串。
        /// </summary>
        internal static string MostRecentThreadAuthorId {
            get {
                return ResourceManager.GetString("MostRecentThreadAuthorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近主题作者名称 的本地化字符串。
        /// </summary>
        internal static string MostRecentThreadAuthorName {
            get {
                return ResourceManager.GetString("MostRecentThreadAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近主题编号 的本地化字符串。
        /// </summary>
        internal static string MostRecentThreadId {
            get {
                return ResourceManager.GetString("MostRecentThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近主题时间 的本地化字符串。
        /// </summary>
        internal static string MostRecentThreadTime {
            get {
                return ResourceManager.GetString("MostRecentThreadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近主题标题 的本地化字符串。
        /// </summary>
        internal static string MostRecentThreadTitle {
            get {
                return ResourceManager.GetString("MostRecentThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近浏览时间 的本地化字符串。
        /// </summary>
        internal static string MostRecentViewedTime {
            get {
                return ResourceManager.GetString("MostRecentViewedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权限 的本地化字符串。
        /// </summary>
        internal static string Permission_None {
            get {
                return ResourceManager.GetString("Permission.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可读 的本地化字符串。
        /// </summary>
        internal static string Permission_Read {
            get {
                return ResourceManager.GetString("Permission.Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可写 的本地化字符串。
        /// </summary>
        internal static string Permission_Write {
            get {
                return ResourceManager.GetString("Permission.Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码 的本地化字符串。
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片路径 的本地化字符串。
        /// </summary>
        internal static string PhotoPath {
            get {
                return ResourceManager.GetString("PhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子 的本地化字符串。
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子编号 的本地化字符串。
        /// </summary>
        internal static string PostId {
            get {
                return ResourceManager.GetString("PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用 的本地化字符串。
        /// </summary>
        internal static string Referer {
            get {
                return ResourceManager.GetString("Referer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用编号 的本地化字符串。
        /// </summary>
        internal static string RefererId {
            get {
                return ResourceManager.GetString("RefererId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可分享性 的本地化字符串。
        /// </summary>
        internal static string Shareability {
            get {
                return ResourceManager.GetString("Shareability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有 的本地化字符串。
        /// </summary>
        internal static string Shareability_All {
            get {
                return ResourceManager.GetString("Shareability.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好友 的本地化字符串。
        /// </summary>
        internal static string Shareability_Frendly {
            get {
                return ResourceManager.GetString("Shareability.Frendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部 的本地化字符串。
        /// </summary>
        internal static string Shareability_Internal {
            get {
                return ResourceManager.GetString("Shareability.Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有 的本地化字符串。
        /// </summary>
        internal static string Shareability_Private {
            get {
                return ResourceManager.GetString("Shareability.Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共 的本地化字符串。
        /// </summary>
        internal static string Shareability_Public {
            get {
                return ResourceManager.GetString("Shareability.Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点 的本地化字符串。
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点编号 的本地化字符串。
        /// </summary>
        internal static string SiteId {
            get {
                return ResourceManager.GetString("SiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 概述简要 的本地化字符串。
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题编号 的本地化字符串。
        /// </summary>
        internal static string ThreadId {
            get {
                return ResourceManager.GetString("ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题状态 的本地化字符串。
        /// </summary>
        internal static string ThreadStatus {
            get {
                return ResourceManager.GetString("ThreadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消 的本地化字符串。
        /// </summary>
        internal static string ThreadStatus_Cancelled {
            get {
                return ResourceManager.GetString("ThreadStatus.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待处理 的本地化字符串。
        /// </summary>
        internal static string ThreadStatus_None {
            get {
                return ResourceManager.GetString("ThreadStatus.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已发布 的本地化字符串。
        /// </summary>
        internal static string ThreadStatus_Published {
            get {
                return ResourceManager.GetString("ThreadStatus.Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间戳 的本地化字符串。
        /// </summary>
        internal static string Tiemstamp {
            get {
                return ResourceManager.GetString("Tiemstamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被踩总数 的本地化字符串。
        /// </summary>
        internal static string TotalDownvotes {
            get {
                return ResourceManager.GetString("TotalDownvotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子总数 的本地化字符串。
        /// </summary>
        internal static string TotalPosts {
            get {
                return ResourceManager.GetString("TotalPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复总数 的本地化字符串。
        /// </summary>
        internal static string TotalReplies {
            get {
                return ResourceManager.GetString("TotalReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题总数 的本地化字符串。
        /// </summary>
        internal static string TotalThreads {
            get {
                return ResourceManager.GetString("TotalThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点赞总数 的本地化字符串。
        /// </summary>
        internal static string TotalUpvotes {
            get {
                return ResourceManager.GetString("TotalUpvotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览总数 的本地化字符串。
        /// </summary>
        internal static string TotalViews {
            get {
                return ResourceManager.GetString("TotalViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string User_Creation {
            get {
                return ResourceManager.GetString("User.Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户邮箱 的本地化字符串。
        /// </summary>
        internal static string User_Email {
            get {
                return ResourceManager.GetString("User.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改时间 的本地化字符串。
        /// </summary>
        internal static string User_Modification {
            get {
                return ResourceManager.GetString("User.Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户电话 的本地化字符串。
        /// </summary>
        internal static string User_Phone {
            get {
                return ResourceManager.GetString("User.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户头像 的本地化字符串。
        /// </summary>
        internal static string UserAvatar {
            get {
                return ResourceManager.GetString("UserAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户编号 的本地化字符串。
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户邮箱 的本地化字符串。
        /// </summary>
        internal static string UserProfile_Email {
            get {
                return ResourceManager.GetString("UserProfile.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户电话 的本地化字符串。
        /// </summary>
        internal static string UserProfile_Phone {
            get {
                return ResourceManager.GetString("UserProfile.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看时间 的本地化字符串。
        /// </summary>
        internal static string ViewedTime {
            get {
                return ResourceManager.GetString("ViewedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可见性 的本地化字符串。
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有 的本地化字符串。
        /// </summary>
        internal static string Visibility_All {
            get {
                return ResourceManager.GetString("Visibility.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        internal static string Visibility_Hidden {
            get {
                return ResourceManager.GetString("Visibility.Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部 的本地化字符串。
        /// </summary>
        internal static string Visibility_Internal {
            get {
                return ResourceManager.GetString("Visibility.Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共 的本地化字符串。
        /// </summary>
        internal static string Visibility_Public {
            get {
                return ResourceManager.GetString("Visibility.Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限定 的本地化字符串。
        /// </summary>
        internal static string Visibility_Specified {
            get {
                return ResourceManager.GetString("Visibility.Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可见 的本地化字符串。
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客地址 的本地化字符串。
        /// </summary>
        internal static string VisitorAddress {
            get {
                return ResourceManager.GetString("VisitorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客描述 的本地化字符串。
        /// </summary>
        internal static string VisitorDescription {
            get {
                return ResourceManager.GetString("VisitorDescription", resourceCulture);
            }
        }
    }
}
